<a href="https://colab.research.google.com/github/IlianRodriguez/Topicos-especiales-II/blob/main/Parciales/Parcial1/Parcial1_IlianRodriguez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---

# **Presentación**

---

**Parcial:** #1  
**Integrantes:**
* Ilian Rodriguez (8-994-2383)
* Kevin Mo (8-1015-2337)  

**Fecha:** 29/09/2026

---

# **1. Cargar el dataset desde la plataforma Moodle**

---

In [1]:
import pandas as pd#importar libreria pandas
import re
#URL del csv en GitHub
urlVentas = "https://raw.githubusercontent.com/IlianRodriguez/Topicos-especiales-II/main/Parciales/Parcial1/Balaji_Fast_Food_Sales.csv"
ventas = pd.read_csv(urlVentas, encoding="utf-8")#UTF-8: lee correctamente caracteres especiales como tildes y ñ.

---

# **2. Análisis exploratorio inicial**

---

In [2]:
print("---------- (1. Dimensiones del dataset) ----------")
print("Cantidad de Filas:", ventas.shape[0])#shape[0]:Cantidad de filas del DataFrame
print("Cantidad de Columnas:", ventas.shape[1])#shape[1]: Cantidad de columnas del DataFrame
print("--------------------------------------------------")
print("Nombres de las Columnas")
print(ventas.columns)#columns: Muestra los nombres de las columnas del DataFrame
print("--------------------------------------------------")
print("Estadísticas de columnas numéricas")
display(ventas.describe())#describe(): Muestra un resumen estadístico de los datos numéricos
print("--------------------------------------------------")
print("No-nulos y Tipos por columnas")
display(ventas.info())#info(): Muestra información general del DataFrame
print("--------------------------------------------------")

---------- (1. Dimensiones del dataset) ----------
Cantidad de Filas: 1000
Cantidad de Columnas: 10
--------------------------------------------------
Nombres de las Columnas
Index(['order_id', 'date', 'item_name', 'item_type', 'item_price', 'quantity',
       'transaction_amount', 'transaction_type', 'received_by',
       'time_of_sale'],
      dtype='object')
--------------------------------------------------
Estadísticas de columnas numéricas

          order_id   item_price     quantity  transaction_amount
count  1000.000000  1000.000000  1000.000000         1000.000000
mean    500.500000    33.315000     8.162000          275.230000
std     288.819436    14.921744     4.413075          204.402979
min       1.000000    20.000000     1.000000           20.000000
25%     250.750000    20.000000     4.000000          120.000000
50%     500.500000    25.000000     8.000000          240.000000
75%     750.250000    50.000000    12.000000          360.000000
max    1000.000000    60.000000    15.000000          900.000000

--------------------------------------------------
No-nulos y Tipos por columnas
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            1000 non-null   int64
 1   date                1000 non-null   object
 2   item_name           1000 non-null   object
 3   item_type           1000 non-null   object
 4   item_price          1000 non-null   int64
 5   quantity            1000 non-null   int64
 6   transaction_amount  1000 non-null   int64
 7   transaction_type    893 non-null    object
 8   received_by         1000 non-null   object
 9   time_of_sale        1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.3+ KB

None

--------------------------------------------------

In [3]:
print("\n-------------- (2. Tipos de datos) ---------------")
print(ventas.dtypes)#dtypes: Muestra el tipo de dato de cada columna
print("--------------------------------------------------")

-------------- (2. Tipos de datos) ---------------
order_id               int64
date                  object
item_name             object
item_type             object
item_price             int64
quantity               int64
transaction_amount     int64
transaction_type      object
received_by           object
time_of_sale          object
dtype: object
--------------------------------------------------

In [4]:
print("\n---------------- (3. Duplicados) -----------------")
print("Ventas exactamentes duplicadas:", ventas.duplicated().sum())#ventas.duplicated().sum(): Cuenta los registros duplicados del DataFrame
print("Ventas con IDs duplicados:", ventas["order_id"].duplicated().sum())#ventas["order_id"].duplicated().sum(): Cuenta los IDs de orden duplicados
print("--------------------------------------------------")

---------------- (3. Duplicados) -----------------
Ventas exactamentes duplicadas: 0
Ventas con IDs duplicados: 0
--------------------------------------------------

In [5]:
print("\n------------------ (4. Nulos) --------------------")
cantidadNulos = ventas.isna().sum()#.isna().sum(): Cuenta los valores nulos por columna
porcentajeNulos = (cantidadNulos / len(ventas) * 100).round(2)#Calcula el porcentaje de valores nulos, redondeado a 2 decimales

display(pd.DataFrame({#Muestra los nulos y sus porcentajes en una tabla.
    "Cantidad": cantidadNulos,
    "%": porcentajeNulos
}))
print("--------------------------------------------------")

------------------ (4. Nulos) --------------------

                    Cantidad     %
order_id                   0   0.0
date                       0   0.0
item_name                  0   0.0
item_type                  0   0.0
item_price                 0   0.0
quantity                   0   0.0
transaction_amount         0   0.0
transaction_type         107  10.7
received_by                0   0.0
time_of_sale               0   0.0

--------------------------------------------------

In [6]:
print("\n-------------- (5. Inconsistencias) ---------------")
print("Valores unicos de cada columna")
print("Item type:", ventas["item_type"].unique())#.unique(): Muestra los valores únicos de una columna
print("Transaction type:", ventas["transaction_type"].unique())
print("Received by:", ventas["received_by"].unique())
print("Time of sale:", ventas["time_of_sale"].unique())
print("--------------------------------------------------")
print("Formato de fechas")#Fecha: MM/DD/YYYY
print("Cumplen(MM/DD/YYYY):", ventas["date"].str.match(r"^\d{2}/\d{2}/\d{4}$").sum())#Cuenta los valores que  coinciden con el patron fecha
print("No cumplen:", (~ventas["date"].str.match(r"^\d{2}/\d{2}/\d{4}$")).sum())#Cuenta los valores que no coinciden con el patron fecha
print("--------------------------------------------------")

-------------- (5. Inconsistencias) ---------------
Valores unicos de cada columna
Item type: ['Fastfood' 'Beverages']
Transaction type: [nan 'Cash' 'Online']
Received by: ['Mr.' 'Mrs.']
Time of sale: ['Night' 'Afternoon' 'Evening' 'Morning' 'Midnight']
--------------------------------------------------
Formato de fechas
Cumplen(MM/DD/YYYY): 159
No cumplen: 841
--------------------------------------------------

In [7]:
print("\n------------------ (6. Memoria) ------------------")
display(pd.DataFrame({
    "Memoria (bytes)": ventas.memory_usage(deep=True, index=False),#Muestra la memoria utilizada por cada columna, en bytes
    "Valores únicos": ventas.nunique()#nunique(): Cuenta la cantidad de valores únicos por columna
}, dtype=object))#dtype=object: convertierte el df a tipo objeto, para que los valores unicos sean enteros y no decimales
print("---------------------------------------------------")

------------------ (6. Memoria) ------------------

                   Memoria (bytes) Valores únicos
order_id                      8000           1000
date                         58562            348
item_name                    58281              7
item_type                    57314              2
item_price                    8000              5
quantity                      8000             15
transaction_amount            8000             48
transaction_type             51587              2
received_by                  52488              2
time_of_sale                 56199              5

---------------------------------------------------

**Problemas de calidad identificados**
* **1. Nulos**
    * La columna transaction_type cuenta con 107 registros nulos, que equivalen al 10.7% de sus registros nulos.
* **2. Inconsistencias**
    * La columna date es de tipo object y cuenta con 841 registros que no cumplen con el formato MM/DD/YYYY.
* **3. Memoria**
    * Las columnas: item_name, item_type, transaction_type, received_by y time_of_sale utilizan una cantidad considerable de memoria en comparación con su número de valores únicos.

---

# **3. Resolución de los problemas de calidad**

---

In [8]:
print("\n------------------ (1. Nulos en transaction_type) ------------------")
print("Columna transaction_type nulos antes")
print(ventas["transaction_type"].value_counts(dropna=False))#Cantidad de cada valor, incluyendo los nulos

ventas["transaction_type"] = ventas["transaction_type"].fillna("No registrado")#fillna(): Reemplaza los valores nulos por "No registrado"

print("\nColumna transaction_type nulos despues")
print(ventas["transaction_type"].value_counts(dropna=False))
print("---------------------------------------------------")

------------------ (1. Nulos en transaction_type) ------------------
Columna transaction_type nulos antes
transaction_type
Cash      476
Online    417
NaN       107
Name: count, dtype: int64

Columna transaction_type nulos despues
transaction_type
Cash             476
Online           417
No registrado    107
Name: count, dtype: int64
---------------------------------------------------

In [9]:
print("\n------ (2. Inconsistencia en formato fecha) -------")# Cuenta las fechas que cumplen con el formato MM/DD/YYYY antes de corregirlas
print("Cantidad de fechas con formato correcto antes (MM/DD/YY): ", ventas["date"].str.match(r"^\d{2}/\d{2}/\d{4}$").sum())
print("Tipo de dato de fecha antes: ",ventas["date"].dtypes)#dtypes: tipo de dato de la fecha

ventas["date"] = pd.to_datetime(ventas["date"], format="mixed")# pd.to_datetime(): Convierte valores a formato de fecha y hora
#format="mixed": Permite convertir fechas con diferentes formatos.

print("\nCantidad de fechas con formato correcto despues (MM/DD/YY): ", ventas["date"].dt.strftime("%m/%d/%Y").str.match(r"^\d{2}/\d{2}/\d{4}$").sum())
print("Tipo de dato de fecha despues: ",ventas["date"].dtypes)
print("---------------------------------------------------")#strftime(): Convierte fechas a un formato de texto
#str.match(): Comprueba si los valores coinciden con un patrón.

------ (2. Inconsistencia en formato fecha) -------
Cantidad de fechas con formato correcto antes (MM/DD/YY):  159
Tipo de dato de fecha antes:  object

Cantidad de fechas con formato correcto despues (MM/DD/YY):  1000
Tipo de dato de fecha despues:  datetime64[ns]
---------------------------------------------------

In [10]:
print("\n------ (3. Espacio en memoria) -------")
print("Espacio de memoria antes")
display(pd.DataFrame({
    "Memoria (bytes)": ventas.memory_usage(deep=True, index=False),#Muestra la memoria utilizada por cada columna, en bytes
    "Valores únicos": ventas.nunique(),#nunique() → Cuenta la cantidad de valores únicos por columna
    "Tipo": ventas.dtypes#dtypes:tipo de datos
}, dtype=object))#dtype=object: convertierte el df a tipo objeto, para que los valores unicos sean enteros y no decimales


columnas_categoria = ["item_name", "item_type", "transaction_type", "received_by", "time_of_sale"]#lista de columnas a cambiar a categoria
ventas[columnas_categoria] = ventas[columnas_categoria].astype("category")# Convierte las columnas seleccionadas al tipo categoria

print("\nEspacio de memoria Despues")
display(pd.DataFrame({
    "Memoria (bytes)": ventas.memory_usage(deep=True, index=False),
    "Valores únicos": ventas.nunique(),
    "Tipo": ventas.dtypes
}, dtype=object))

print("---------------------------------------------------")

------ (3. Espacio en memoria) -------
Espacio de memoria antes

                   Memoria (bytes) Valores únicos            Tipo
order_id                      8000           1000           int64
date                          8000            348  datetime64[ns]
item_name                    58281              7          object
item_type                    57314              2          object
item_price                    8000              5           int64
quantity                      8000             15           int64
transaction_amount            8000             48           int64
transaction_type             54797              3          object
received_by                  52488              2          object
time_of_sale                 56199              5          object

Espacio de memoria Despues

                   Memoria (bytes) Valores únicos            Tipo
order_id                      8000           1000           int64
date                          8000            348  datetime64[ns]
item_name                     1707              7        category
item_type                     1223              2        category
item_price                    8000              5           int64
quantity                      8000             15           int64
transaction_amount            8000             48           int64
transaction_type              1278              3        category
received_by                   1213              2        category
time_of_sale                  1453              5        category

---------------------------------------------------

**Problemas de calidad resueltos**
* **1. Nulos**
    * Se reemplazaron los valores nulos de transaction_type por "No registrado", ya que representan el 10.7% de los registros. No se utilizó la moda porque Cash (476) y Online (417) tienen cantidades similares, y asignar los 107 nulos a Cash aumentaría artificialmente la diferencia entre ambas categorías.
* **2. Inconsistencias**
    * Se convirtió la columna date a formato datetime, ya que presentaba diferentes formas de representar las fechas, como meses con uno o dos dígitos. Después de la conversión, los 1,000 registros cumplen con el formato MM/DD/YYYY.
* **3. Memoria**
    * Se convirtieron las columnas item_name, item_type, transaction_type, received_by y time_of_sale al tipo category, ya que contienen pocos valores únicos que se repiten en muchos registros. Esto permite reducir el espacio de memoria utilizado por el DataFrame sin modificar los valores de los datos.

---

# **4. Traducción de datos a español**

---

In [11]:
print("\n---------------- (1. Valores originales en ingles) -----------------")
print("Item type:", ventas["item_type"].unique())
print("Item name:", ventas["item_name"].unique())
print("Time of sale:", ventas["time_of_sale"].unique())
print("Transaction type:", ventas["transaction_type"].unique())
print("---------------------------------------------------")

---------------- (1. Valores originales en ingles) -----------------
Item type: ['Fastfood', 'Beverages']
Categories (2, object): ['Beverages', 'Fastfood']
Item name: ['Aalopuri', 'Vadapav', 'Sugarcane juice', 'Panipuri', 'Frankie', 'Sandwich', 'Cold coffee']
Categories (7, object): ['Aalopuri', 'Cold coffee', 'Frankie', 'Panipuri', 'Sandwich',
                         'Sugarcane juice', 'Vadapav']
Time of sale: ['Night', 'Afternoon', 'Evening', 'Morning', 'Midnight']
Categories (5, object): ['Afternoon', 'Evening', 'Midnight', 'Morning', 'Night']
Transaction type: ['No registrado', 'Cash', 'Online']
Categories (3, object): ['Cash', 'No registrado', 'Online']
---------------------------------------------------

In [12]:
#Listas para traducir los valores a español
TraduccionColumnas = {
    "order_id": "ID de orden",
    "date": "Fecha",
    "item_name": "Nombre del producto",
    "item_type": "Tipo de producto",
    "item_price": "Precio del producto",
    "quantity": "Cantidad",
    "transaction_amount": "Monto de la transacción",
    "transaction_type": "Medio de pago",
    "received_by": "Recibido por",
    "time_of_sale": "Turno de venta"
}

TraduccionItemName = {
    "Aalopuri": "Aalopuri",            #Sin traduccion adecuada al espanol, se mantiene el nombre original (plato tipico indio)
    "Vadapav": "Vadapav",              #Sin traduccion adecuada al espanol, se mantiene el nombre original (plato tipico indio)
    "Sugarcane juice": "Jugo de caña",
    "Panipuri": "Panipuri",            #Sin traduccion adecuada al espanol, se mantiene el nombre original (plato tipico indio)
    "Frankie": "Frankie",              #Nombre propio del producto, se mantiene igual
    "Sandwich": "Emparedado",
    "Cold coffee": "Café frío"
}

TraduccionItemType = {
    "Fastfood": "Comida rápida",
    "Beverages": "Bebidas"
}

TraduccionTransactionType = {
    "Cash": "Efectivo",
    "Online": "En línea",
    "No registrado": "No registrado"  #El valor ya se encuentra en español
}

TraduccionReceivedBy = {
    "Mr.": "Sr.",
    "Mrs.": "Sra."
}
TraduccionTimeOfSale = {
    "Morning": "Mañana",
    "Afternoon": "Tarde",
    "Evening": "Anochecer",
    "Night": "Noche",
    "Midnight": "Medianoche"
}

print("\n---------------- (2. Valores traducidos al español) -----------------")
print("Columnas:", ventas.rename(columns=TraduccionColumnas).columns.tolist())
print("Nombre de Producto: ",ventas["item_name"].map(TraduccionItemName).astype(str).unique())
print("Categoria de Producto: ",ventas["item_type"].map(TraduccionItemType).astype(str).unique())
print("Tipo de transaccion: ",ventas["transaction_type"].map(TraduccionTransactionType).astype(str).unique())
print("Atendido por: ",ventas["received_by"].map(TraduccionReceivedBy).astype(str).unique())
print("Tiempo de Venta: ",ventas["time_of_sale"].map(TraduccionTimeOfSale).astype(str).unique())
print("---------------------------------------------------")

---------------- (2. Valores traducidos al español) -----------------
Columnas: ['ID de orden', 'Fecha', 'Nombre del producto', 'Tipo de producto', 'Precio del producto', 'Cantidad', 'Monto de la transacción', 'Medio de pago', 'Recibido por', 'Turno de venta']
Nombre de Producto:  ['Aalopuri' 'Vadapav' 'Jugo de caña' 'Panipuri' 'Frankie' 'Emparedado'
 'Café frío']
Categoria de Producto:  ['Comida rápida' 'Bebidas']
Tipo de transaccion:  ['No registrado' 'Efectivo' 'En línea']
Atendido por:  ['Sr.' 'Sra.']
Tiempo de Venta:  ['Noche' 'Tarde' 'Anochecer' 'Mañana' 'Medianoche']
---------------------------------------------------

**Justificación de la traducción**  
* En item_name, **Aalopuri**, **Vadapav**, **Panipuri** y **Frankie** son platillos de comida callejera india sin una traducción adecuada al español (no existe una palabra equivalente que describa el platillo); se decidió mantener el nombre original, ya que traducirlos literalmente (por ejemplo, palabra por palabra) perdería el significado del producto. Solo **Sugarcane juice** y **Cold coffee** tenían una traducción natural (Jugo de caña, Café frío) y se tradujeron.
* Los nombres de tipo de producto (item_type), turno (time_of_sale) y medio de pago (transaction_type) tienen equivalente directo en español y se tradujeron por completo.

---

# **Guardar y cargar Dataset Limpio**

---

In [13]:
print("---------- (1. Exportar el dataset limpio) ----------")
try:
    ventas.to_csv("Balaji_Fast_Food_Sales_Limpio.csv", index=False, encoding="utf-8-sig")
    print("El archivo se exportó con éxito.")
except Exception as e:
    print(f"Error al exportar el archivo: {e}")

---------- (1. Exportar el dataset limpio) ----------
El archivo se exportó con éxito.

In [14]:
print("---------- (2. Cargar el dataset limpio) ----------")
ventasLimpioUrl = "https://github.com/IlianRodriguez/Topicos-especiales-II/raw/refs/heads/main/Parciales/Parcial1/Balaji_Fast_Food_Sales_Limpio.csv"
ventasLimpio = pd.read_csv(ventasLimpioUrl, encoding="utf-8-sig")
print("Dataframe cargado con exito")

---------- (2. Cargar el dataset limpio) ----------
Dataframe cargado con exito

In [15]:
print("---------- (3. Convertit data a date_time) ----------")
print("date tipo antes: ",ventasLimpio["date"].dtype)
ventasLimpio["date"] = pd.to_datetime(ventas["date"], format="mixed")
print("date tipo despues: ", ventasLimpio["date"].dtype)

---------- (3. Convertit data a date_time) ----------
date tipo antes:  object
date tipo despues:  datetime64[ns]

**Justificación**
* Se exportó el DataFrame limpio a un nuevo archivo CSV para conservar una versión preparada para el análisis. Luego, se cargó nuevamente en un nuevo DataFrame para trabajar sobre los datos limpios.

* Al cargarlo, la columna date se convirtió nuevamente a datetime, ya que el formato CSV no conserva los tipos de datos de Pandas. Esto permite realizar correctamente el análisis de fechas.

---

# **5. Reportes**

---

### **1. Reporte por medio de pago**

In [16]:
mediosPago = ventasLimpio[ventasLimpio["transaction_type"].isin(["Cash", "Online"])].groupby("transaction_type").agg(#groupby(): agrupa por medio de pago
    Ventas_Totales=("order_id", "count"),#isin(): selecciona Cash y Online
    Monto_Total=("transaction_amount", "sum")
)

mediosPago["(%)_Ventas"] = mediosPago["Ventas_Totales"] / len(ventasLimpio) * 100# Calcula el porcentaje de ventas
mediosPago["(%)_Monto"] = mediosPago["Monto_Total"] / ventasLimpio["transaction_amount"].sum() * 100# Calcula el porcentaje del monto
mediosPago.index.name = TraduccionColumnas["transaction_type"]# Traduce los resultados

print("-------------------- (1. Reporte por medio de pago) -------------------")
display(mediosPago.rename(index=TraduccionTransactionType).round(2))
print("-----------------------------------------------------------------------")

-------------------- (1. Reporte por medio de pago) -------------------

               Ventas_Totales  Monto_Total  (%)_Ventas  (%)_Monto
Medio de pago
Efectivo                  476       132840        47.6      48.27
En línea                  417       110595        41.7      40.18

-----------------------------------------------------------------------

**Hallazgos**
* Efectivo: 476 ventas y 47.6% del total.
* En línea: 417 ventas y 41.7% del total.
* Efectivo generó mayor monto total: 132,840.

**Método de detección**
* isin(), groupby() y agg() para filtrar, agrupar y calcular.
* count para ventas y sum para montos.

### **2. Reporte de productos por turno**

In [17]:
productos = ["Cold coffee", "Panipuri", "Sandwich"]

cantidadProductos = ventasLimpio[ventasLimpio["item_name"].isin(productos)].pivot_table(#pivot_table(): crea una tabla resumen
    index="item_name",
    columns="time_of_sale",
    values="quantity",
    aggfunc="sum",
    observed=True,
    fill_value=0
)

cantidadProductos = cantidadProductos.reindex(columns=["Morning", "Afternoon", "Evening", "Night", "Midnight"])#Organiza los turnos en orden
cantidadProductos = cantidadProductos.rename(index=TraduccionItemName,columns=TraduccionTimeOfSale)
cantidadProductos.index.name = TraduccionColumnas["item_name"]# rename(): traduce nombres en la salida
cantidadProductos.columns.name = TraduccionColumnas["time_of_sale"]

print("------------ (2. Cantidad de productos vendidos por turnos) -----------")
display(cantidadProductos)
print("-----------------------------------------------------------------------")

------------ (2. Cantidad de productos vendidos por turnos) -----------

Turno de venta       Mañana  Tarde  Anochecer  Noche  Medianoche
Nombre del producto
Café frío               287    337        235    299         203
Panipuri                233    230        241    244         278
Emparedado              234    164        206    292         201

-----------------------------------------------------------------------

**Hallazgos**
* Café frío: mayor cantidad en la mañana (287).
* Café frío: mayor cantidad en la tarde (337).
* Panipuri: mayor cantidad en anochecer (278).
* Emparedado: mayor cantidad en la noche (292).
* Panipuri: mayor cantidad en medianoche (278).

**Método de detección**
* isin() para seleccionar los productos.
* pivot_table() y sum para obtener las cantidades por turno.
* reindex() para ordenar los turnos.

### **3. Reporte de tipo de producto por medio de pago**

In [18]:
tipoProductoMedioPago = pd.pivot_table(
    ventasLimpio,
    index="item_type",
    columns="transaction_type",
    values="order_id",
    aggfunc="count",
    observed=True,
    fill_value=0
)

tipoProductoMedioPago = tipoProductoMedioPago.rename(index=TraduccionItemType,columns=TraduccionTransactionType)
tipoProductoMedioPago.index.name = TraduccionColumnas["item_type"]# rename(): traduce los nombres en la salida
tipoProductoMedioPago.columns.name = TraduccionColumnas["transaction_type"]

print("-- (3. Cantidad de ventas de cada tipo de producto por medio de pago) --")
display(tipoProductoMedioPago)
print("-----------------------------------------------------------------------")

-- (3. Cantidad de ventas de cada tipo de producto por medio de pago) --

Medio de pago     Efectivo  No registrado  En línea
Tipo de producto
Bebidas                148             40       126
Comida rápida          328             67       291

-----------------------------------------------------------------------

**Hallazgos**
* Comida rápida tiene más ventas: 328 en efectivo y 291 en línea.
* Bebidas tiene 148 ventas en efectivo y 126 en línea.
* Hay 107 ventas sin medio de pago registrado.

Método de detección
**bold text*** pivot_table() para cruzar tipo de producto y medio de pago.
* count para contar las ventas.
* fill_value=0 para reemplazar valores vacíos.

### **4. Reporte de producto más vendido**

In [19]:
unidadesVendidas = pd.pivot_table(
    ventasLimpio,
    index="item_name",
    columns=ventasLimpio["date"].dt.month,# dt.month: obtiene el número del mes
    values="quantity",
    aggfunc="sum",# sum: suma las unidades vendidas
    fill_value=0# Reemplaza los valores vacíos por 0
).reindex(columns=range(1, 13), fill_value=0)# reindex(): asegura los 12 meses

ingresosGenerados = pd.pivot_table(
    ventasLimpio,
    index="item_name",
    columns=ventasLimpio["date"].dt.month,# dt.month: obtiene el número del mes
    values="transaction_amount",
    aggfunc="sum",
    fill_value=0
).reindex(columns=range(1, 13), fill_value=0)# reindex(): asegura los 12 meses

reporte = pd.DataFrame({
    "Producto más vendido": unidadesVendidas.idxmax(),# idxmax(): obtiene el producto con mayor cantidad
    "Unidades vendidas": unidadesVendidas.max(),# max(): obtiene la cantidad máxima
    "Producto con mayor ingreso": ingresosGenerados.idxmax(),# idxmax(): obtiene el producto con mayor ingreso
    "Ingreso generados": ingresosGenerados.max()# max(): obtiene el ingreso máximo
})
#Ordena los meses en texto
reporte.index = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio","Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
reporte.index.name = "Mes"

print("--------------- (4. Producto con más cantidades vendidas y con mayores ingresos por meses de manera global) ---------------")
display(reporte)
print("---------------------------------------------------------------------------------------------------------------------------")

--------------- (4. Producto con más cantidades vendidas y con mayores ingresos por meses de manera global) ---------------

,Producto más vendido,Unidades vendidas,Producto con mayor ingreso,Ingreso generados
Mes,,,,
Enero,Frankie,153,Sandwich,8580
Febrero,Frankie,166,Frankie,8300
Marzo,Cold coffee,142,Sandwich,6900
Abril,Sandwich,125,Sandwich,7500
Mayo,Aalopuri,191,Frankie,6850
Junio,Frankie,128,Frankie,6400
Julio,Sugarcane juice,122,Sandwich,5400
Agosto,Cold coffee,151,Cold coffee,6040
Septiembre,Sandwich,93,Sandwich,5580
Octubre,Cold coffee,156,Cold coffee,6240
Noviembre,Panipuri,178,Cold coffee,6160
Diciembre,Sugarcane juice,152,Cold coffee,6040

---------------------------------------------------------------------------------------------------------------------------

**Hallazgos**
* Frankie fue el más vendido en 3 meses.
* Sandwich obtuvo el mayor ingreso en 5 meses.
* Enero tuvo el mayor ingreso: 8,580.

**Método de detección**
* pivot_table() para resumir unidades e ingresos por mes y producto.
* dt.month para obtener el mes.
* idxmax() para identificar el producto con mayor valor.
* max() para obtener la cantidad o ingreso máximo.

---

# **6. Reportes adicionales**

---

### **1. Ingresos trimestrales del año 2022**
¿Cómo se distribuyen los montos totales de las transacciones durante los trimestres del año 2022?

In [20]:
montosTrimestre = pd.pivot_table(
    ventasLimpio[ventasLimpio["date"].dt.year == 2022],# Filtra las ventas de 2022
    index=ventasLimpio["date"].dt.quarter, # Obtiene el trimestre
    values="transaction_amount",
    aggfunc="sum",# Suma los montos
    fill_value=0
).reindex([1, 2, 3, 4], fill_value=0) # Fuerza a incluir los 4 trimestres
# Calcula el porcentaje de cada trimestre
montosTrimestre["Porcentaje"] = (montosTrimestre["transaction_amount"] /montosTrimestre["transaction_amount"].sum() * 100)
#Ordena los trimestres por rangos de meses
montosTrimestre.index = ["Enero - Marzo", "Abril - Junio", "Julio - Septiembre", "Octubre - Diciembre"]

montosTrimestre.index.name = "Trimestre"
montosTrimestre = montosTrimestre.rename(columns={# Traduce el nombre de la columna
    "transaction_amount": "Monto total"
})

print("-------------------- (1. Transacciones por trimestres del año 2022) -------------------")
display(montosTrimestre.round(2))
print("-----------------------------------------------------------------------")

-------------------- (1. Transacciones por trimestres del año 2022) -------------------

                     Monto total  Porcentaje
Trimestre
Enero - Marzo                  0        0.00
Abril - Junio              61575       31.48
Julio - Septiembre         60435       30.90
Octubre - Diciembre        73565       37.61

-----------------------------------------------------------------------

**Hallazgos**
* Enero - Marzo: no registró ventas.
* Octubre - Diciembre: tuvo el mayor monto, con $73,565 (37.61%).
* Abril - Junio y Julio - Septiembre tuvieron montos similares.

**Método de comprobación**
* pivot_table() para agrupar los montos por trimestre.
* sum para obtener el monto total.
* Cálculo del porcentaje respecto al total de 2022.

**Decisiones tomadas**
* Se incluyeron los cuatro trimestres aunque uno no tuviera ventas.
* Los trimestres sin ventas se representaron con 0.
* Se utilizaron rangos de meses para facilitar la interpretación.

**Recomendaciones de negocio**
* Investigar y solicitar las causas por que no hay ventas en el primer trimestre.
* Analizar los productos vendidos en el cuarto semestre con mayores ventas.
* Planificar estrategias para aumentar las ventas en el segundo y tercer trimestre del año.

### **2. Ordenes de Panipuri por franjas horarias**
¿En qué franjas horarias se concentra la mayor cantidad de órdenes de Panipuri?

In [21]:
ordenesPanipuri = pd.pivot_table(
    ventasLimpio[ventasLimpio["item_name"] == "Panipuri"],# Filtra las órdenes de Panipuri
    index="time_of_sale",
    values="order_id",
    aggfunc="count",# Cuenta las órdenes
    fill_value=0
).reindex(["Morning", "Afternoon", "Evening", "Night", "Midnight"],fill_value=0)# Ordena las franjas horarias

ordenesPanipuri["Porcentaje"] = (ordenesPanipuri["order_id"] /ordenesPanipuri["order_id"].sum() * 100)# Calcula el porcentaje de cada franja

ordenesPanipuri = ordenesPanipuri.rename(index=TraduccionTimeOfSale,columns={"order_id": "Cantidad de órdenes"})# Traduce los resultados
ordenesPanipuri.index.name = TraduccionColumnas["time_of_sale"]

print("-------------------- (2. Órdenes de Panipuri por franja horaria) -------------------")
display(ordenesPanipuri.round(2))
print("------------------------------------------------------------------------------------")

-------------------- (2. Órdenes de Panipuri por franja horaria) -------------------

                Cantidad de órdenes  Porcentaje
Turno de venta
Mañana                           29       19.33
Tarde                            28       18.67
Anochecer                        36       24.00
Noche                            26       17.33
Medianoche                       31       20.67

------------------------------------------------------------------------------------

**Hallazgos**
* Anochecer concentra la mayor cantidad de órdenes: 36 (24%).
* Noche presenta la menor cantidad: 26 (17.33%).
* Las órdenes están relativamente distribuidas entre las cinco franjas.

**Método de comprobación**
* pivot_table() para agrupar las órdenes por franja horaria.
* count para contar las órdenes de Panipuri.
* Cálculo del porcentaje respecto al total de órdenes.

**Decisiones tomadas**
* Se consideraron únicamente las órdenes de Panipuri.
* Se incluyeron todas las franjas horarias, incluso si alguna no tuviera órdenes.
* Se mantuvo el orden lógico de las franjas.

**Recomendaciones de negocio**
* Reforzar la disponibilidad de Panipuri durante el anochecer, donde se concentra la mayor cantidad de órdenes.
* Mantener una distribución de  personal acorde con la demanda de cada franja.

---

# **7. Indicadores clave de desempeño (KPI)**

---

### **1. Tipo de producto con mayor número de órdenes**
Qué tipo de producto concentra la mayor cantidad de órdenes?

In [22]:
ordenesTipo = ventasLimpio.groupby("item_type")["order_id"].count()#groupby: Cuenta las órdenes por tipo

tipoMayor = ordenesTipo.idxmax()# Obtiene el tipo con más órdenes
cantidadMayor = ordenesTipo.max()# Obtiene la cantidad máxima de órdenes

print("------------------- (1. Tipo de producto con mayor número de órdenes) --------------")
print(f"El tipo de producto con mayor número de órdenes es: {TraduccionItemType[tipoMayor]} con {cantidadMayor} órdenes")
print("------------------------------------------------------------------------------------")

------------------- (1. Tipo de producto con mayor número de órdenes) --------------
El tipo de producto con mayor número de órdenes es: Comida rápida con 686 órdenes
------------------------------------------------------------------------------------

**¿Qué mide?**
* Identifica el tipo de producto que concentra la mayor cantidad de órdenes.

**Resultado**
* La Comida rápida con 686 órdenes, es la categoria de productos que mas ordenes genera.

**Decisión de negocio**
* Mantener suficiente inventario de productos de comida rápida para evitar faltantes.
* Revisar cuáles productos específicos dentro de esta categoría tienen mayor demanda.
* Evaluar si conviene aumentar la disponibilidad de estos productos en los horarios de mayor demanda.

### **2. Participación de ventas de bebidas en el 2023**
qué porcentaje de las ventas de 2023 corresponde a productos de la categoría Bebidas.

In [23]:
ventas2023 = ventasLimpio[ventasLimpio["date"].dt.year == 2023]
ventasBebidas = ventas2023[ventas2023["item_type"] == "Beverages"]["order_id"].count()
ventasTotales = ventas2023["order_id"].count()
participacionBebidas = ventasBebidas / ventasTotales * 100

print("------------------- (2. Participación de ventas de bebidas en 2023) -------------------")
print(f"Las bebidas representan el {participacionBebidas:.2f}% de las ventas del 2023")
print("----------------------------------------------------------------------------------------")

------------------- (2. Participación de ventas de bebidas en 2023) -------------------
Las bebidas representan el 29.92% de las ventas del 2023
----------------------------------------------------------------------------------------

**Qué mide?**
* Mide qué porcentaje de las ventas realizadas en 2023 corresponde a productos de la categoría Bebidas.

**Resultado**
* 29.92% de las ventas de 2023 corresponden a bebidas.

**Decisiones de negocio**
* Revisar la disponibilidad de bebidas para mantener una oferta adecuada.
* Evaluar promociones para incrementar la participación de esta categoría.
* Identificar cuáles bebidas generan mayor demanda para asegurar su inventario.

---

# **8. Hallazgos dirigidos al dueño del restaurante**

---

**Hallazgos**
1. Algunas ventas realizadas no tienen registrado el medio de pago, lo que dificulta conocer con precisión cómo pagan los clientes.
2. La información sobre quién recibe las ventas es poco detallada. Se recomienda registrar el nombre o identificador  del empleado en cada venta.
3. La comida rápida es el punto más fuerte del negocio.
4. El emparedado es el producto estrella del restaurante, ya que, es el  mas ingresos genera.
5. La noche es el turno con mayor volumen de ventas. Esto indica que durante este período existe una mayor carga de trabajo